name = "Hyperopt"
uuid = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
author = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "0.3.3"

[deps]
BayesianOptimization = "4c6ed407-134f-591c-93fa-e0f7c164a0ec"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BayesianOptimization = "0.2"
GaussianProcesses = "0.12"
Juno = "0.7, 0.8"
LatinHypercubeSampling = "1.2"
Lazy = "0.13, 0.14, 0.15"
MacroTools = "0.5"
Parameters = "0.11, 0.12"
RecipesBase = "0.7, 0.8, 1.0"
julia = "1.0"

[extras]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Optim", "Plots"]
